### ISSUE TITLE
Reintroduce supervisord as dependency 

### ISSUE THREAD

**Issue by urosgruber** [urosgruber/datadog-agent-FreeBSD#16]
Datadog is moving towards supervisord for all daemons and (start|stop|restart) commands will be removed in datadog 5.11

**Comment by RainbowHackerHorse** [comment]
Be that as it may, that doesn't really fit within the FreeBSD way of doing things. I'd leave it as an optional dependency (if you're still working on this).
As far as FreeBSD is concerned, the rc system should be what's starting and stopping daemons by default. I'm happy to help get your port into the tree and provide any feedback or assistance I can, as a FreeBSD Ports Maintainer myself.
If you don't have an rc.d script for dd-agent yet, you'll probably want one, as that's how FreeBSD is going to start/stop/restart/reload the daemon.

**Comment by urosgruber** [comment]
@RainbowHackerHorse I would like to continue with this but since no one really respond to my PR on FreeBSD bugs I just maintain my own code.

During this period a lot of stuff changed and Datadog is now written in GO since version 6 so I'm not sure it it's worth pursuing version 5.x or go straight to 6. But as I said they are using supervisord which I don't like at all so any help around this would be greatly appreciated.

**Comment by irabinovitch** [comment]
@urosgruber Starting in the 6.x release cycle we're no longer using supervisord for the Datadog Agent which may simplify porting.

**Comment by RainbowHackerHorse** [comment]
@urosgruber I pinged the guy who grabbed the submission; he extends his apologies and while I'm sure it unfortunately has, it shouldn't be taken as how the FreeBSD Project does things usually. This was an accident, and if you look at your bug submission, you'll see an update :)

> Datadog is now written in GO since version 6 so I'm not sure it it's worth pursuing version 5.x or go straight to 6

Go is terrible, but absolutely a supported language on FreeBSD!
If you want to sit down at some point and talk, I'd love to help you bring the port up to date and submit the newest version :)

If you need help with the rc.d script as well, lemme know!

As I believe I mentioned before, I'm not (currently) a committer, only a maintainer, so I won't be able to directly commit your port, but I can definitely open the PR for you when you're ready, and ask someone with a commit bit to take a look!

**Comment by urosgruber** [comment]
Closing this in favour of v7
