### ISSUE TITLE
Working 7.16 version

### ISSUE THREAD

**Issue by fzipi** [urosgruber/datadog-agent-FreeBSD#19]
Hi @urosgruber ,

We have a working pkg for the 7.16.0 version. I guess we could join forces to push it to ports at some point.

Regards,
Felipe.

**Comment by urosgruber** [comment]
@fzipi I would be more than happy if someone could help. This package gets so many changes and maintaining this is not an easy task.

**Comment by ryanmaclean** [comment]
@fzipi if I can help here at all, lmk!

**Comment by fzipi** [comment]
@ryanmaclean Sure. We have splitted the package in two: one for the agent itself, and one for the integrations.

**Comment by Corvan** [comment]
Hey @fzipi, care to share the pkg/port you  have? How did you get it to build without the cgroup error?
Cheers
Lars

**Comment by Corvan** [comment]
See also: https://github.com/DataDog/datadog-agent/issues/6623

**Comment by fzipi** [comment]
Truly sorry. I did forgot to include the link. We created two packages: https://github.com/Perceptyx/datadog-agent, and https://github.com/Perceptyx/datadog-integrations. Please let me know if it works for you.

**Comment by Corvan** [comment]
thank you, will have a look at it

**Comment by urosgruber** [comment]
I've opened new PR #22 with 7.17.1

It's the last one that builds without an issue. With 7.18 things become much more complicated and with 7.19 cgroup is introduced.

**Comment by Corvan** [comment]
I am glad that I can report a success. Thank you very much @urosgruber !
I was able to build it in my dev environment. I shall put it into our poudriere by tomorrow and see if it builds there, too, but I am not expecting problems at the moment.

**Comment by urosgruber** [comment]
I'll close this one since there is a newer version available. Feel free to open in case something is not resolved or open new issue.
