### ISSUE TITLE
Submit new FreeBSD port

### ISSUE THREAD

**Issue by urosgruber** [urosgruber/datadog-agent-FreeBSD#2]

**Comment by urosgruber** [comment]
Submited https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208560

Waiting for reply and possible updates

**Comment by mheppner** [comment]
Any updates? It looks like as of a month ago, `sysutils/py-uptime` is now in the ports tree. Anything I can provide assistance with?

**Comment by urosgruber** [comment]
I pushed latest changes to this repo but latest version have so much Docker related code and patching is a pain. If you can help with this I would be more than happy.

**Comment by mheppner** [comment]
I'll see what I can do. You pretty much just want all of the Docker utils removed, right? Since I'm new to making new ports, can I just run the Makefile in any directory, or do I have to put it somewhere in the ports tree?

**Comment by urosgruber** [comment]
So I don't see a reason to have Docker code available. So I'm just trying to comment out things. You can add this repo under `/ports/sysutils/datadog` and update `/ports/GIDs` and `/ports/UIDs` with the content of the files in this repo. After that you will be able to run make.

**Comment by mheppner** [comment]
Thanks. I'll send you a PR if I make any progress.

**Comment by urosgruber** [comment]
New port submited https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208561

**Comment by mheppner** [comment]
I just checked out master in a clean VM, compiled it, and everything works great. Thanks for working on this :)

**Comment by urosgruber** [comment]
@mheppner if you can upvote on bugzilla would be nice to speed things up a bit.

**Comment by ryanmaclean** [comment]
Looks like the port submitted got some attention, but triage is asking for an update to 6.X at least ❤️

**Comment by urosgruber** [comment]
@ryanmaclean I think it's worth updating to 7.x. Since it's not that big of a change as it was between 5 and 6. Thoughts?

**Comment by urosgruber** [comment]
FreeBSD port is not available. https://www.freshports.org/sysutils/datadog/ Thank you all for all the tests and feedback. I'm doing a new version as well as there is a repo with integrations I'm planning to release soon.
