### ISSUE TITLE
distinfo out of date? 

### ISSUE THREAD

**Issue by laffer1** [urosgruber/datadog-agent-FreeBSD#20]
Looks like the file sizes increased on some of the files fetched by this port. I think you need to regenerate the distinfo file.

**Comment by urosgruber** [comment]
@laffer1 what version are you referring to?

**Comment by laffer1** [comment]
The v6 branch.

**Comment by urosgruber** [comment]
@laffer1 please check https://github.com/urosgruber/dd-agent-FreeBSD/tree/v7-next . I'm closing this one since I don't have a plan to work on v6.
