### ISSUE TITLE
Error with dd-agent group

### ISSUE THREAD

**Issue by MikeJakubik** [urosgruber/datadog-agent-FreeBSD#24]
Hi,

I am getting the following error when building the port.

Thanks.

Successfully wrote /tmp/dd-agent-FreeBSD/work/datadog-agent-7.17.1/cmd/agent/dist/datadog.yaml
===>  Staging for datadog-7.17.1
===>   datadog-7.17.1 depends on package: py39-yaml>0 - found
===>   datadog-7.17.1 depends on file: /usr/local/bin/python3.9 - found
===>   Generating temporary packing list
===> Creating groups.
** Cannot find any information about group `dd-agent' in /tmp/dd-agent-FreeBSD/files/GIDs.
*** Error code 1

Stop.
make: stopped in /tmp/dd-agent-FreeBSD

FreeBSD jailer.local 12.2-STABLE FreeBSD 12.2-STABLE r367155 JAILER  amd64

**Comment by urosgruber** [comment]
@MikeJakubik please check https://github.com/urosgruber/dd-agent-FreeBSD/pull/23

**Comment by MikeJakubik** [comment]
I tried doing a git switch v7-next but got this error.

(install  -m 444 /tmp/dd-agent-FreeBSD/work/datadog-agent-7.23.1/README.md /tmp/dd-agent-FreeBSD/work/stage/usr/local/share/doc/datadog)
install: /tmp/dd-agent-FreeBSD/work/datadog-agent-7.23.1/README.md: No such file or directory

I renamed the version in the Makefile, but still no go.

cd /tmp/dd-agent-FreeBSD/work/datadog-agent-7.17.1/pkg/status && /bin/sh -c '(/usr/bin/find -Ed $1 $3 | /usr/bin/cpio -dumpl $2 >/dev/null 2>&1) &&  /usr/bin/find -Ed $1 $3 \(   -type d -exec /bin/sh -c '\''cd '\''$2'\'' && chmod 755 "$@"'\'' . {} +  -o -type f -exec /bin/sh -c '\''cd '\''$2'\'' && chmod 0644 "$@"'\'' . {} + \)' COPYTREE_SHARE templates /tmp/dd-agent-FreeBSD/work/stage/usr/local/bin/datadog/dist
find: templates: No such file or directory
find: templates: No such file or directory
*** Error code 1

Sorry, im a git noob.

**Comment by urosgruber** [comment]
You probably need to clean the folder or just create a fresh checkout from this branch.

**Comment by MikeJakubik** [comment]
That did the job! Thank you for making this port btw, don't know why DD can't be bothered to support FreeBSD.

FYI, I had to change the ownership of /usr/local/etc/datadog for it to be able to write it's auth token.

Some of the metrics don't work, such as process mem and network usage. I found the following in the log.

2020-11-06 14:38:00 EST | CORE | ERROR | (pkg/collector/embed_python.go:18 in pySetup) | Could not initialize Python: could not initialize rtloader: could not import base class: No module named 'datadog_checks'
2020-11-06 14:38:00 EST | CORE | ERROR | (pkg/collector/scheduler.go:201 in GetChecksFromConfigs) | Unable to load the check: unable to load any check from config 'apm'
2020-11-06 14:38:00 EST | CORE | ERROR | (pkg/collector/scheduler.go:201 in GetChecksFromConfigs) | Unable to load the check: unable to load any check from config 'network'
2020-11-06 14:38:02 EST | CORE | ERROR | (pkg/collector/corechecks/loader.go:67 in Load) | core.loader: could not configure check Process Agent: Can't access the default process-agent binary at /usr/local/embedded/bin/process-agent
2020-11-06 14:38:02 EST | CORE | ERROR | (pkg/collector/scheduler.go:201 in GetChecksFromConfigs) | Unable to load the check: unable to load any check from config 'process_agent'
2020-11-06 14:38:02 EST | CORE | ERROR | (pkg/collector/scheduler.go:201 in GetChecksFromConfigs) | Unable to load the check: unable to load any check from config 'winproc'

**Comment by urosgruber** [comment]
@MikeJakubik this port does not include any checks but just some legacy that I'm planning to remove. Please use https://github.com/urosgruber/datadog-integrations as a separate port and it will install some integrations. I need to take some time to include what is actually useful on FreeBSD. 

Regarding the first line I think there must be some issue on your end. I'll try on a clean machine to see if it's missing something.

**Comment by MikeJakubik** [comment]
It might because im using Python 3.9, i noticed this issue on make install with the integrations, as you can see it wants 3.7.

pkg-static: Unable to access file /tmp/datadog-integrations/work/stage/usr/local/lib/python3.9/site-packages/datadog_checks/utils/__pycache__/containers.cpython-37.pyc:No such file or directory

**Comment by MikeJakubik** [comment]
I figured out the Python dependency issue, needed to install requests_unixsocket and typing_extensions. Also, had to set dd_agent_bin: /usr/local/bin/datadog/process-agent to main config, though it still wants /usr/local/embedded/bin/process-agent, maybe my Yaml is messed up. Also, not sure about these, i.e. it seems to think we want winproc, but i see not reference to this in the configs.

Datadog’s apm integration is reporting:
Instance #initialization[ERROR]: {"Core Check Loader":"Check apm not found in Catalog","Python Check Loader":"unable to import module 'apm': No module named 'apm'"}
Datadog’s network integration is reporting:
Instance #initialization[ERROR]: {"Core Check Loader":"Check network not found in Catalog","Python Check Loader":"unable to import module 'network': No module named 'network'"}
Datadog’s process_agent integration is reporting:
Instance #initialization[ERROR]: {"Core Check Loader":"Could not configure check Process Agent: Can't access the default process-agent binary at /usr/local/embedded/bin/process-agent","Python Check Loader":"unable to import module 'process_agent': No module named 'process_agent'"}
Datadog’s winproc integration is reporting:
Instance #initialization[ERROR]: {"Core Check Loader":"Check winproc not found in Catalog","Python Check Loader":"unable to import module 'winproc': No module named 'winproc'"}

**Comment by urosgruber** [comment]
@MikeJakubik thanks. Now I remember I created also requests_unixsocket port but was not yet committed to the BSD repo. Maybe commenting to https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250727 would help bump this up
