### ISSUE TITLE
process-agent leaking memory

### ISSUE THREAD

**Issue by MikeJakubik** [urosgruber/datadog-agent-FreeBSD#25]
The process seems to be leaking memory, it took down my whole system which has 4GB swap and 100GB RAM.

Nov  9 11:24:27 jailer kernel: pid 3500 (process-agent), jid 0, uid 480, was killed: out of swap space
Nov  9 11:24:37 jailer kernel: pid 18209 (process-agent), jid 0, uid 480, was killed: out of swap space
Nov  9 11:24:40 jailer kernel: pid 13562 (process-agent), jid 0, uid 480, was killed: out of swap space

**Comment by urosgruber** [comment]
Might be something to ask datadog team. I'll see if the same happening on one of my machines. How long it took to fill the RAM?

**Comment by MikeJakubik** [comment]
> Might be something to ask datadog team. I'll see if the same happening on one of my machines. How long it took to fill the RAM?

Not long, about 15min.

[root@jailer ~]# python3 --version
Python 3.9.0
[root@jailer ~]# uname -a
FreeBSD jailer.local 12.2-STABLE FreeBSD 12.2-STABLE r367155 JAILER  amd64

**Comment by urosgruber** [comment]
I tested on my machine and I can't see any leaks. Please try the latest master.

**Comment by MikeJakubik** [comment]
I think you can safely ignore this, seems to be an issue with my system, not specific to the agent.

**Comment by urosgruber** [comment]
Ok, closing this.
