### ISSUE TITLE
How to install dd-agent-freebsd from the github .zip file?

### ISSUE THREAD

**Issue by ljimber** [urosgruber/datadog-agent-FreeBSD#8]
Hi, Thanks for taking this on, we are a all FreeBSD shop and checking out datadoghq. 

I have downloaded your git hub zip file but #pkg add ./dd-FreeBSD-master does not work, looks like pkg add wants a file ending in .tgz 

Any pointers on how to install locally?

Thanks!
Lee

**Comment by urosgruber** [comment]
This is just port definition and you need to build it manually into pkg. If you're not familiar with this you need to wait for this to be included in main ports tree or I can run build on my build server and attach pkg from where you can install it with `pkg add`

I'm currently waiting for next version of datadog agent because it will include one patch I upstreamed and I still didn't decide about how to start all the necessary deamons.

**Comment by ljimber** [comment]
Thank you!

I would greatly appreciate a package built from your local server if thats
not too much trouble :)

Cheers!

Lee

On Tue, Feb 23, 2016 at 1:42 PM, Uroš Gruber notifications@github.com
wrote:

> This is just port definition and you need to build it manually into pkg.
> If you're not familiar with this you need to wait for this to be included
> in main ports tree or I can run build on my build server and attach pkg
> from where you can install it with pkg add
> 
> I'm currently waiting for next version of datadog agent because it will
> include one patch I upstreamed and I still didn't decide about how to start
> all the necessary deamons.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/urosgruber/dd-agent-FreeBSD/issues/8#issuecomment-187835975
> .

##

**Comment by urosgruber** [comment]
What is you base 10.2?

**Comment by ljimber** [comment]
10.0 or 10.1 at the moment. If only 10.2 I can try that.

Thanks!

On Tue, Feb 23, 2016 at 1:53 PM, Uroš Gruber notifications@github.com
wrote:

> What is you base 10.2?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/urosgruber/dd-agent-FreeBSD/issues/8#issuecomment-187840008
> .

## 

Lee

**Comment by urosgruber** [comment]
Can you try to download

http://pkg.squarebox.eu/packages/FreeBSD:10:amd64/All/datadog-5.6.2.txz

and then install with `pkg add ./datadog-5.6.2.txz`

**Comment by ljimber** [comment]
Hi Uros,

Here are my install notes.

OS: FreeBSD-10.1-RELEASE-p15 running in AWS.

I had to install number of y27 dependancies (full notes at end).

py27-requests
py27-psutil
py27-tornado
py27-boto
py27-supervisor
py27-simplejson
py27-ntplib
py27-yaml

The "notes" at the end of the install need to be corrected.

_"The dd-agent port has been installed with an example config file, located_
_in /usr/local/etc/dd-agent.conf.sample."_

This should be /usr/local/etc/datadog.conf.sample

_Before starting the daemon, copy /usr/local/etc/dd-agent.conf.sample to_
_/usr/local/etc/dd-agent.conf and update "api_key" with DataDog API key_
_avaliable https://app.datadoghq.com/account/settings#api
https://app.datadoghq.com/account/settings#api"_

/usr/local/etc/datadog.conf.sample to /usr/local/etc/datadog.conf

---

I added my API key and added datadog_enable="YES" to rc.conf.

#/usr/local/etc/rc.d/datadog start

root     5101   0.0  1.0 103552  21596  -  Ss    2:19PM      0:00.04
/usr/local/bin/python2.7 /usr/local/bin/supervisord -u root -c
/usr/local/etc/datadog/supervisord.conf
root     5102   0.0  1.2 134112  25056  -  S     2:19PM      0:00.29
/usr/local/bin/python2.7
/usr/local/lib/python2.7/site-packages/datadog/dogstatsd.py
--use-local-forwarder
root     5103   0.0  1.2 136604  25564  -  S     2:19PM      0:00.36
/usr/local/bin/python2.7
/usr/local/lib/python2.7/site-packages/datadog/ddagent.py
--use_simple_http_client=1
root     5104   0.0  1.3 135004  26336  -  S     2:19PM      0:00.40
/usr/local/bin/python2.7
/usr/local/lib/python2.7/site-packages/datadog/agent.py foreground
--use-local-forwarder

Datadog does seem to be running, however, I am not getting any data into
datadoghq.

Here is the log contents of forwarder.log

2016-02-24 14:23:51 UTC | WARNING | dd.forwarder |
tornado.general(iostream.py:1276) | SSL Error on 11 ('50.16.207.250', 443):
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
2016-02-24 14:23:51,085 | WARNING | dd.forwarder |
tornado.general(iostream.py:1276) | SSL Error on 11 ('50.16.207.250', 443):
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
2016-02-24 14:23:51,087 | ERROR | dd.forwarder | forwarder(ddagent.py:262)
| Response: HTTPResponse(_body=None,buffer=None,code=599,effective_url='
https://5-6-2-app.agent.datadoghq.com/intake/?api_key=REMOVED',error=SSLError(1,
u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
(_ssl.c:590)'),headers=<tornado.httputil.HTTPHeaders object at
0x8088ec0d0>,reason='Unknown',request=<tornado.httpclient.HTTPRequest
object at 0x808b58f50>,request_time=0.00783395767211914,time_info={})
2016-02-24 14:23:51 UTC | ERROR | dd.forwarder | forwarder(ddagent.py:262)
| Response: HTTPResponse(_body=None,buffer=None,code=599,effective_url='
https://5-6-2-app.agent.datadoghq.com/intake/?api_key=REMOVED',error=SSLError(1,
u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
(_ssl.c:590)'),headers=<tornado.httputil.HTTPHeaders object at
0x8088ec0d0>,reason='Unknown',request=<tornado.httpclient.HTTPRequest
object at 0x808b58f50>,request_time=0.00783395767211914,time_info={})
2016-02-24 14:23:51,106 | WARNING | dd.forwarder |
transaction(transaction.py:213) | Transaction 38 in error (1 error), it
will be replayed after 2016-02-24 14:24:11
2016-02-24 14:23:51 UTC | WARNING | dd.forwarder |
transaction(transaction.py:213) | Transaction 38 in error (1 error), it
will be replayed after 2016-02-24 14:24:11

There seems to be a SSL issue with python. For some reason this smells
familiar with me but I don't remember why. I will see what I can find. I
think I am close!

Thank you again for you time and work on this port. Any progress I make I
will let you know.

--------FULL INSTALL NOTES-----

root@cs1-lab:/home/lee # pkg add ./datadog-5.6.2.txz
Installing datadog-5.6.2...
pkg: Missing dependency 'py27-requests'

Failed to install the following 1 package(s): ./datadog-5.6.2.txz
root@cs1-lab:/home/lee # pkg install py27-requests
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
Fetching packagesite.txz: 100%    5 MiB   5.6MB/s    00:01
Processing entries: 100%
FreeBSD repository update completed. 24898 packages processed.
New version of pkg detected; it needs to be installed first.
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
pkg: 1.6.3 -> 1.6.4

The process will require 1 KiB more space.
2 MiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching pkg-1.6.4.txz: 100%    2 MiB   2.5MB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Upgrading pkg from 1.6.3 to 1.6.4...
[1/1] Extracting pkg-1.6.4: 100%
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
py27-requests: 2.9.1

The process will require 3 MiB more space.
494 KiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching py27-requests-2.9.1.txz: 100%  494 KiB 505.8kB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Installing py27-requests-2.9.1...
[1/1] Extracting py27-requests-2.9.1: 100%
root@cs1-lab:/home/lee # pkg add ./datadog-5.6.2.txz
Installing datadog-5.6.2...
pkg: Missing dependency 'py27-psutil'

Failed to install the following 1 package(s): ./datadog-5.6.2.txz
root@cs1-lab:/home/lee # pkg install py27-psutil
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
py27-psutil: 3.3.0

The process will require 647 KiB more space.
101 KiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching py27-psutil-3.3.0.txz: 100%  101 KiB 103.0kB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Installing py27-psutil-3.3.0...
[1/1] Extracting py27-psutil-3.3.0: 100%
root@cs1-lab:/home/lee # pkg add ./datadog-5.6.2.txz
Installing datadog-5.6.2...
pkg: Missing dependency 'py27-tornado'

Failed to install the following 1 package(s): ./datadog-5.6.2.txz
root@cs1-lab:/home/lee # pkg install py27-tornado
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 6 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
py27-tornado: 4.3
py27-backports_abc: 0.4
python2: 2_3
py27-singledispatch: 3.4.0.3
py27-certifi: 2015.11.20
py27-futures: 3.0.3

The process will require 5 MiB more space.
733 KiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching py27-tornado-4.3.txz: 100%  534 KiB 546.5kB/s    00:01
Fetching py27-backports_abc-0.4.txz: 100%    5 KiB   5.3kB/s    00:01
Fetching python2-2_3.txz: 100%    1 KiB   1.1kB/s    00:01
Fetching py27-singledispatch-3.4.0.3.txz: 100%   12 KiB  12.4kB/s    00:01
Fetching py27-certifi-2015.11.20.txz: 100%  163 KiB 166.8kB/s    00:01
Fetching py27-futures-3.0.3.txz: 100%   19 KiB  19.0kB/s    00:01
Checking integrity... done (0 conflicting)
[1/6] Installing python2-2_3...
[1/6] Extracting python2-2_3: 100%
[2/6] Installing py27-backports_abc-0.4...
[2/6] Extracting py27-backports_abc-0.4: 100%
[3/6] Installing py27-singledispatch-3.4.0.3...
[3/6] Extracting py27-singledispatch-3.4.0.3: 100%
[4/6] Installing py27-certifi-2015.11.20...
[4/6] Extracting py27-certifi-2015.11.20: 100%
[5/6] Installing py27-futures-3.0.3...
[5/6] Extracting py27-futures-3.0.3: 100%
[6/6] Installing py27-tornado-4.3...
[6/6] Extracting py27-tornado-4.3: 100%
root@cs1-lab:/home/lee # pkg add ./datadog-5.6.2.txz
Installing datadog-5.6.2...
pkg: Missing dependency 'py27-boto'

Failed to install the following 1 package(s): ./datadog-5.6.2.txz
root@cs1-lab:/home/lee # pkg install py27-boto
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
py27-boto: 2.38.0

The process will require 13 MiB more space.
1 MiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching py27-boto-2.38.0.txz: 100%    1 MiB   1.2MB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Installing py27-boto-2.38.0...
[1/1] Extracting py27-boto-2.38.0: 100%
root@cs1-lab:/home/lee # pkg add ./datadog-5.6.2.txz
Installing datadog-5.6.2...
pkg: Missing dependency 'py27-supervisor'

Failed to install the following 1 package(s): ./datadog-5.6.2.txz
root@cs1-lab:/home/lee # pkg install py27-supervisor
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 2 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
py27-supervisor: 3.0_1,1
py27-meld3: 0.6.8_1

The process will require 4 MiB more space.
503 KiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching py27-supervisor-3.0_1,1.txz: 100%  459 KiB 470.5kB/s    00:01
Fetching py27-meld3-0.6.8_1.txz: 100%   43 KiB  44.5kB/s    00:01
Checking integrity... done (0 conflicting)
[1/2] Installing py27-meld3-0.6.8_1...
[1/2] Extracting py27-meld3-0.6.8_1: 100%
[2/2] Installing py27-supervisor-3.0_1,1...
[2/2] Extracting py27-supervisor-3.0_1,1: 100%
root@cs1-lab:/home/lee # pkg add ./datadog-5.6.2.txz
Installing datadog-5.6.2...
pkg: Missing dependency 'py27-simplejson'

Failed to install the following 1 package(s): ./datadog-5.6.2.txz
root@cs1-lab:/home/lee # pkg install py27-simplejson
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
py27-simplejson: 3.8.1

The process will require 523 KiB more space.
80 KiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching py27-simplejson-3.8.1.txz: 100%   80 KiB  82.2kB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Installing py27-simplejson-3.8.1...
[1/1] Extracting py27-simplejson-3.8.1: 100%
root@cs1-lab:/home/lee # pkg add ./datadog-5.6.2.txz
Installing datadog-5.6.2...
pkg: Missing dependency 'py27-ntplib'

Failed to install the following 1 package(s): ./datadog-5.6.2.txz
root@cs1-lab:/home/lee # pkg install py27-ntplib
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
py27-ntplib: 0.3.3

The process will require 42 KiB more space.
9 KiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching py27-ntplib-0.3.3.txz: 100%    9 KiB   8.9kB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Installing py27-ntplib-0.3.3...
[1/1] Extracting py27-ntplib-0.3.3: 100%
root@cs1-lab:/home/lee # pkg add ./datadog-5.6.2.txz
Installing datadog-5.6.2...
pkg: Missing dependency 'py27-yaml'

Failed to install the following 1 package(s): ./datadog-5.6.2.txz
root@cs1-lab:/home/lee # pkg install py27-yaml
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
py27-yaml: 3.11

The process will require 584 KiB more space.
77 KiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching py27-yaml-3.11.txz: 100%   77 KiB  79.1kB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Installing py27-yaml-3.11...
[1/1] Extracting py27-yaml-3.11: 100%
root@cs1-lab:/home/lee # pkg add ./datadog-5.6.2.txz
Installing datadog-5.6.2...
===> Creating users and/or groups.
Creating group 'datadog' with gid '900'.
Creating user 'datadog' with uid '900'.
usage: install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 file2
       install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 ... fileN directory
       install -dU [-vU] [-g group] [-m mode] [-N dbdir] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               directory ...
pkg: PRE-INSTALL script failed
Extracting datadog-5.6.2: 100%

# Message from datadog-5.6.2:

The dd-agent port has been installed with an example config file, located
in /usr/local/etc/dd-agent.conf.sample.

Before starting the daemon, copy /usr/local/etc/dd-agent.conf.sample to
/usr/local/etc/dd-agent.conf and update "api_key" with DataDog API key
avaliable https://app.datadoghq.com/account/settings#api

# 

root@cs1-lab:/home/lee #

On Tue, Feb 23, 2016 at 7:03 PM, Uroš Gruber notifications@github.com
wrote:

> Can you try to download
> 
> http://pkg.squarebox.eu/packages/FreeBSD:10:amd64/All/datadog-5.6.2.txz
> 
> and then install with pkg add ./datadog-5.6.2.txz
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/urosgruber/dd-agent-FreeBSD/issues/8#issuecomment-187976255
> .

## 

Lee

**Comment by urosgruber** [comment]
@ljimber can you try with new version 

http://pkg.squarebox.eu/packages/FreeBSD:10:amd64/All/datadog-5.6.3.txz

I also included basic rc.init script

**Comment by ljimber** [comment]
Thank You! 

Here are the latest installer notes, much better!

root@1202111:~lee # pkg install ./datadog-5.6.3.txz
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
Fetching packagesite.txz: 100%    5 MiB   5.6MB/s    00:01
Processing entries: 100%
FreeBSD repository update completed. 24934 packages processed.
New version of pkg detected; it needs to be installed first.
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
    pkg: 1.6.2 -> 1.6.4_1

The process will require 12 KiB more space.
2 MiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching pkg-1.6.4_1.txz: 100%    2 MiB   2.5MB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Upgrading pkg from 1.6.2 to 1.6.4_1...
[1/1] Extracting pkg-1.6.4_1: 100%
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 12 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
    datadog: 5.6.3
    py27-requests: 2.9.1
    py27-psutil: 3.3.0
    py27-tornado: 4.3
    py27-backports_abc: 0.4
    py27-singledispatch: 3.4.0.3
    py27-certifi: 2015.11.20
    py27-futures: 3.0.5
    py27-boto: 2.38.0
    py27-simplejson: 3.8.1
    py27-ntplib: 0.3.3
    py27-yaml: 3.11

The process will require 25 MiB more space.
3 MiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching py27-requests-2.9.1.txz: 100%  493 KiB 504.9kB/s    00:01
Fetching py27-psutil-3.3.0.txz: 100%  101 KiB 103.0kB/s    00:01
Fetching py27-tornado-4.3.txz: 100%  534 KiB 546.6kB/s    00:01
Fetching py27-backports_abc-0.4.txz: 100%    5 KiB   5.3kB/s    00:01
Fetching py27-singledispatch-3.4.0.3.txz: 100%   12 KiB  12.4kB/s    00:01
Fetching py27-certifi-2015.11.20.txz: 100%  163 KiB 166.7kB/s    00:01
Fetching py27-futures-3.0.5.txz: 100%   19 KiB  19.0kB/s    00:01
Fetching py27-boto-2.38.0.txz: 100%    1 MiB   1.2MB/s    00:01
Fetching py27-simplejson-3.8.1.txz: 100%   80 KiB  82.2kB/s    00:01
Fetching py27-ntplib-0.3.3.txz: 100%    9 KiB   8.9kB/s    00:01
Fetching py27-yaml-3.11.txz: 100%   77 KiB  79.1kB/s    00:01
Checking integrity... done (0 conflicting)
[1/12] Installing py27-backports_abc-0.4...
[1/12] Extracting py27-backports_abc-0.4: 100%
[2/12] Installing py27-singledispatch-3.4.0.3...
[2/12] Extracting py27-singledispatch-3.4.0.3: 100%
[3/12] Installing py27-certifi-2015.11.20...
[3/12] Extracting py27-certifi-2015.11.20: 100%
[4/12] Installing py27-futures-3.0.5...
[4/12] Extracting py27-futures-3.0.5: 100%
[5/12] Installing py27-requests-2.9.1...
[5/12] Extracting py27-requests-2.9.1: 100%
[6/12] Installing py27-psutil-3.3.0...
[6/12] Extracting py27-psutil-3.3.0: 100%
[7/12] Installing py27-tornado-4.3...
[7/12] Extracting py27-tornado-4.3: 100%
[8/12] Installing py27-boto-2.38.0...
[8/12] Extracting py27-boto-2.38.0: 100%
[9/12] Installing py27-simplejson-3.8.1...
[9/12] Extracting py27-simplejson-3.8.1: 100%
[10/12] Installing py27-ntplib-0.3.3...
[10/12] Extracting py27-ntplib-0.3.3: 100%
[11/12] Installing py27-yaml-3.11...
[11/12] Extracting py27-yaml-3.11: 100%
[12/12] Installing datadog-5.6.3...
===> Creating users and/or groups.
Creating group 'datadog' with gid 485.
Creating user 'datadog' with uid 485.
[12/12] Extracting datadog-5.6.3: 100%

# Message from datadog-5.6.3:

The dd-agent port has been installed with an example config file, located
in /usr/local/etc/datadog/datadog.conf.sample.

Before starting the daemon, edit /usr/local/etc/datadog/datadog.conf and
update "api_key" with DataDog API key
avaliable https://app.datadoghq.com/account/settings#api

# 

root@1202111:~lee #

Final Notes:

Very nice! I simply added my api key to /usr/local/etc/datadog/datadog.conf then added data datadog_enable="YES" to /etc/rc.conf and finally /usr/local/etc/rc.d/datadog-agent start and I have a machine reporting to the dashboard!

Thank you again! 

Cheers, 

Lee

**Comment by urosgruber** [comment]
Great, thanks for testing.
